Document: pebl-language
Title: Debian pebl-language Manual
Author: <insert document author here>
Abstract: This manual describes what pebl-language is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pebl-language/pebl-language.sgml.gz

Format: postscript
Files: /usr/share/doc/pebl-language/pebl-language.ps.gz

Format: text
Files: /usr/share/doc/pebl-language/pebl-language.text.gz

Format: HTML
Index: /usr/share/doc/pebl-language/html/index.html
Files: /usr/share/doc/pebl-language/html/*.html
