#!/bin/sh
inkscape --without-gui  --export-height=300 --export-png=pngs/nat00.png svgs/nat00.svg
inkscape --without-gui  --export-height=300 --export-png=pngs/nat01.png svgs/nat01.svg
inkscape --without-gui  --export-width=300 --export-png=pngs/nat02.png svgs/nat02.svg
inkscape --without-gui  --export-height=300 --export-png=pngs/nat03.png svgs/nat03.svg
inkscape --without-gui  --export-width=300 --export-png=pngs/nat04.png svgs/nat04.svg
inkscape --without-gui  --export-height=300 --export-png=pngs/nat05.png svgs/nat05.svg
inkscape --without-gui  --export-height=300 --export-png=pngs/nat06.png svgs/nat06.svg
inkscape --without-gui  --export-height=300 --export-png=pngs/nat07.png svgs/nat07.svg
inkscape --without-gui  --export-height=300 --export-png=pngs/nat08.png svgs/nat08.svg
inkscape --without-gui  --export-height=300 --export-png=pngs/nat09.png svgs/nat09.svg
inkscape --without-gui  --export-width=300 --export-png=pngs/man00.png svgs/man00.svg
inkscape --without-gui  --export-height=300 --export-png=pngs/man01.png svgs/man01.svg
inkscape --without-gui  --export-width=300 --export-png=pngs/man02.png svgs/man02.svg
inkscape --without-gui  --export-height=300 --export-png=pngs/man03.png svgs/man03.svg
inkscape --without-gui  --export-height=300 --export-png=pngs/man04.png svgs/man04.svg
inkscape --without-gui  --export-width=300 --export-png=pngs/man05.png svgs/man05.svg
inkscape --without-gui  --export-width=300 --export-png=pngs/man06.png svgs/man06.svg
inkscape --without-gui  --export-height=300 --export-png=pngs/man07.png svgs/man07.svg
inkscape --without-gui  --export-height=300 --export-png=pngs/man08.png svgs/man08.svg
inkscape --without-gui  --export-width=300 --export-png=pngs/man09.png svgs/man09.svg
